# Add accessibility to results:
paste -d ',' functional-lncrna-exon1-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/functional-lncrna-exon1-accessibility-feature.csv) > functional-lncrna-exon1-dataset-features_1.csv
paste -d ',' functional-lncrna-exon2-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/functional-lncrna-exon2-accessibility-feature.csv) > functional-lncrna-exon2-dataset-features_1.csv
paste -d ',' functional-protein-exon2-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/functional-protein-exon2-accessibility-feature.csv) > functional-protein-exon2-dataset-features_1.csv
paste -d ',' functional-protein-exon3-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/functional-protein-exon3-accessibility-feature.csv) > functional-protein-exon3-dataset-features_1.csv
paste -d ',' functional-short-ncrna-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/functional-short-ncrna-accessibility-feature.csv) > functional-short-ncrna-dataset-features_1.csv
paste -d ',' lncrna-exon1-negative-control-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/lncrna-exon1-negative-control-accessibility-feature.csv) > lncrna-exon1-negative-control-dataset-features_1.csv
paste -d ',' lncrna-exon2-negative-control-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/lncrna-exon2-negative-control-accessibility-feature.csv) > lncrna-exon2-negative-control-dataset-features_1.csv
paste -d ',' protein-exon2-negative-control-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/protein-exon2-negative-control-accessibility-feature.csv) > protein-exon2-negative-control-dataset-features_1.csv
paste -d ',' protein-exon3-negative-control-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/protein-exon3-negative-control-accessibility-feature.csv) > protein-exon3-negative-control-dataset-features_1.csv
paste -d ',' short-ncrna-negative-control-dataset-features.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/accessibility_feature/short-ncrna-negative-control-accessibility-feature.csv) > short-ncrna-negative-control-dataset-features_1.csv

# Add fickett score to results:
paste -d ',' functional-lncrna-exon1-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/functional-lncrna-exon1-fickett-feature.csv) > functional-lncrna-exon1-dataset-features_2.csv
paste -d ',' functional-lncrna-exon2-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/functional-lncrna-exon2-fickett-feature.csv) > functional-lncrna-exon2-dataset-features_2.csv
paste -d ',' functional-protein-exon2-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/functional-protein-exon2-fickett-feature.csv) > functional-protein-exon2-dataset-features_2.csv
paste -d ',' functional-protein-exon3-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/functional-protein-exon3-fickett-feature.csv) > functional-protein-exon3-dataset-features_2.csv
paste -d ',' functional-short-ncrna-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/functional-short-ncrna-fickett-feature.csv) > functional-short-ncrna-dataset-features_2.csv
paste -d ',' lncrna-exon1-negative-control-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/lncrna-exon1-negative-control-fickett-feature.csv) > lncrna-exon1-negative-control-dataset-features_2.csv
paste -d ',' lncrna-exon2-negative-control-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/lncrna-exon2-negative-control-fickett-feature.csv) > lncrna-exon2-negative-control-dataset-features_2.csv
paste -d ',' protein-exon2-negative-control-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/protein-exon2-negative-control-fickett-feature.csv) > protein-exon2-negative-control-dataset-features_2.csv
paste -d ',' protein-exon3-negative-control-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/protein-exon3-negative-control-fickett-feature.csv) > protein-exon3-negative-control-dataset-features_2.csv
paste -d ',' short-ncrna-negative-control-dataset-features_1.csv <(cut -d ',' -f 1 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/datasets/fickett_feature/short-ncrna-negative-control-fickett-feature.csv) > short-ncrna-negative-control-dataset-features_2.csv

# Add GERP 91 mammals
paste -d ',' functional-lncrna-exon1-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-lncrna-exon1-mammals-gerp-feature.csv) > functional-lncrna-exon1-dataset-features_3.csv
paste -d ',' functional-lncrna-exon2-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-lncrna-exon2-mammals-gerp-feature.csv) > functional-lncrna-exon2-dataset-features_3.csv
paste -d ',' functional-protein-exon2-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-protein-exon2-mammals-gerp-feature.csv) > functional-protein-exon2-dataset-features_3.csv
paste -d ',' functional-protein-exon3-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-protein-exon3-mammals-gerp-feature.csv) > functional-protein-exon3-dataset-features_3.csv
paste -d ',' functional-short-ncrna-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-short-ncrna-mammals-gerp-feature.csv) > functional-short-ncrna-dataset-features_3.csv
paste -d ',' lncrna-exon1-negative-control-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/lncrna-exon1-negative-control-mammals-gerp-feature.csv) > lncrna-exon1-negative-control-dataset-features_3.csv
paste -d ',' lncrna-exon2-negative-control-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/lncrna-exon2-negative-control-mammals-gerp-feature.csv) > lncrna-exon2-negative-control-dataset-features_3.csv
paste -d ',' protein-exon2-negative-control-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/protein-exon2-negative-control-mammals-gerp-feature.csv) > protein-exon2-negative-control-dataset-features_3.csv
paste -d ',' protein-exon3-negative-control-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/protein-exon3-negative-control-mammals-gerp-feature.csv) > protein-exon3-negative-control-dataset-features_3.csv
paste -d ',' short-ncrna-negative-control-dataset-features_2.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/short-ncrna-negative-control-mammals-gerp-feature.csv) > short-ncrna-negative-control-dataset-features_3.csv

# Add GERP 63 amniotes
paste -d ',' functional-lncrna-exon1-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-lncrna-exon1-amniotes-gerp-feature.csv) > functional-lncrna-exon1-dataset-features_4.csv
paste -d ',' functional-lncrna-exon2-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-lncrna-exon2-amniotes-gerp-feature.csv) > functional-lncrna-exon2-dataset-features_4.csv
paste -d ',' functional-protein-exon2-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-protein-exon2-amniotes-gerp-feature.csv) > functional-protein-exon2-dataset-features_4.csv
paste -d ',' functional-protein-exon3-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-protein-exon3-amniotes-gerp-feature.csv) > functional-protein-exon3-dataset-features_4.csv
paste -d ',' functional-short-ncrna-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/functional-short-ncrna-amniotes-gerp-feature.csv) > functional-short-ncrna-dataset-features_4.csv
paste -d ',' lncrna-exon1-negative-control-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/lncrna-exon1-negative-control-amniotes-gerp-feature.csv) > lncrna-exon1-negative-control-dataset-features_4.csv
paste -d ',' lncrna-exon2-negative-control-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/lncrna-exon2-negative-control-amniotes-gerp-feature.csv) > lncrna-exon2-negative-control-dataset-features_4.csv
paste -d ',' protein-exon2-negative-control-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/protein-exon2-negative-control-amniotes-gerp-feature.csv) > protein-exon2-negative-control-dataset-features_4.csv
paste -d ',' protein-exon3-negative-control-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/protein-exon3-negative-control-amniotes-gerp-feature.csv) > protein-exon3-negative-control-dataset-features_4.csv
paste -d ',' short-ncrna-negative-control-dataset-features_3.csv <(cut -d ',' -f 2 ~/Downloads/Estefi/Otago\ University/RsyncCopy/epigenetic-marks-analysis/data/GERP_feature/short-ncrna-negative-control-amniotes-gerp-feature.csv) > short-ncrna-negative-control-dataset-features_4.csv

# Rename file into original
mv functional-lncrna-exon1-dataset-features_4.csv functional-lncrna-exon1-dataset-features.csv
mv functional-lncrna-exon2-dataset-features_4.csv functional-lncrna-exon2-dataset-features.csv
mv functional-protein-exon2-dataset-features_4.csv functional-protein-exon2-dataset-features.csv
mv functional-protein-exon3-dataset-features_4.csv functional-protein-exon3-dataset-features.csv
mv functional-short-ncrna-dataset-features_4.csv functional-short-ncrna-dataset-features.csv

mv lncrna-exon1-negative-control-dataset-features_4.csv lncrna-exon1-negative-control-dataset-features.csv
mv lncrna-exon2-negative-control-dataset-features_4.csv lncrna-exon2-negative-control-dataset-features.csv
mv protein-exon2-negative-control-dataset-features_4.csv protein-exon2-negative-control-dataset-features.csv
mv protein-exon3-negative-control-dataset-features_4.csv protein-exon3-negative-control-dataset-features.csv
mv short-ncrna-negative-control-dataset-features_4.csv short-ncrna-negative-control-dataset-features.csv
